BEGIN;

CREATE TABLE hospitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    mobile VARCHAR(20),
    address TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE platform_superusers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    mobile VARCHAR(10) NOT NULL UNIQUE CHECK (mobile ~ '^[0-9]{10}$'),
    email VARCHAR(180) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE hospitals
    ADD COLUMN deactivated_at TIMESTAMPTZ,
    ADD COLUMN deactivated_by_superuser BIGINT REFERENCES platform_superusers(id);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
    name VARCHAR(120) NOT NULL,
    mobile VARCHAR(10) NOT NULL CHECK (mobile ~ '^[0-9]{10}$'),
    email VARCHAR(180),
    password_hash TEXT NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN','DOCTOR','RECEPTIONIST')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    UNIQUE (hospital_id, id)
);

CREATE UNIQUE INDEX users_hospital_mobile_key
    ON users(hospital_id, mobile);
CREATE UNIQUE INDEX users_hospital_email_key
    ON users(hospital_id, lower(email)) WHERE email IS NOT NULL;

CREATE TABLE super_admin_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    superuser_id BIGINT NOT NULL REFERENCES platform_superusers(id),
    action VARCHAR(50) NOT NULL CHECK (action IN ('LOGIN','IMPERSONATE_ADMIN','IMPERSONATE_USER','DEACTIVATE_HOSPITAL','ACTIVATE_HOSPITAL')),
    hospital_id BIGINT REFERENCES hospitals(id),
    target_user_id BIGINT REFERENCES users(id),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_super_admin_audit_created ON super_admin_audit_logs(superuser_id,created_at DESC);

CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
    full_name VARCHAR(160) NOT NULL,
    mobile VARCHAR(20) NOT NULL,
    gender VARCHAR(20) CHECK (gender IS NULL OR gender IN ('MALE','FEMALE','OTHER','PREFER_NOT_TO_SAY')),
    date_of_birth DATE,
    address TEXT,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    UNIQUE (hospital_id, id),
    FOREIGN KEY (hospital_id, created_by) REFERENCES users(hospital_id, id),
    FOREIGN KEY (hospital_id, updated_by) REFERENCES users(hospital_id, id)
);

CREATE INDEX idx_patients_hospital_mobile ON patients(hospital_id, mobile) WHERE deleted_at IS NULL;
CREATE INDEX idx_patients_hospital_name ON patients(hospital_id, lower(full_name)) WHERE deleted_at IS NULL;

CREATE TABLE billing_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
    name VARCHAR(140) NOT NULL,
    default_price NUMERIC(12,2) NOT NULL CHECK (default_price >= 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    UNIQUE (hospital_id, name),
    UNIQUE (hospital_id, id),
    FOREIGN KEY (hospital_id, created_by) REFERENCES users(hospital_id, id),
    FOREIGN KEY (hospital_id, updated_by) REFERENCES users(hospital_id, id)
);

CREATE TABLE visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
    visit_number BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'WAITING_FOR_DOCTOR'
        CHECK (status IN ('WAITING_FOR_DOCTOR','WITH_DOCTOR','PAYMENT_PENDING','COMPLETED','CANCELLED','LEFT_BEFORE_DOCTOR','LEFT_WITHOUT_PAYMENT')),
    doctor_billing_finalized BOOLEAN NOT NULL DEFAULT FALSE,
    doctor_notes TEXT,
    doctor_notes_updated_at TIMESTAMPTZ,
    doctor_notes_updated_by BIGINT,
    created_by BIGINT NOT NULL,
    completed_by BIGINT,
    completed_at TIMESTAMPTZ,
    cancelled_by BIGINT,
    cancelled_at TIMESTAMPTZ,
    left_by BIGINT,
    left_at TIMESTAMPTZ,
    left_note VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (hospital_id, id),
    UNIQUE (hospital_id, visit_number),
    FOREIGN KEY (hospital_id, patient_id) REFERENCES patients(hospital_id, id),
    FOREIGN KEY (hospital_id, doctor_id) REFERENCES users(hospital_id, id),
    FOREIGN KEY (hospital_id, doctor_notes_updated_by) REFERENCES users(hospital_id, id),
    FOREIGN KEY (hospital_id, created_by) REFERENCES users(hospital_id, id),
    FOREIGN KEY (hospital_id, completed_by) REFERENCES users(hospital_id, id),
    FOREIGN KEY (hospital_id, cancelled_by) REFERENCES users(hospital_id, id),
    FOREIGN KEY (hospital_id, left_by) REFERENCES users(hospital_id, id)
);

CREATE INDEX idx_visits_hospital_created ON visits(hospital_id, created_at DESC);
CREATE INDEX idx_visits_doctor_status ON visits(hospital_id, doctor_id, status);
CREATE INDEX idx_visits_patient ON visits(hospital_id, patient_id, created_at DESC);

CREATE TABLE hospital_visit_counters (
    hospital_id BIGINT PRIMARY KEY REFERENCES hospitals(id) ON DELETE CASCADE,
    next_number BIGINT NOT NULL CHECK (next_number > 0)
);

CREATE TABLE visit_doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
    visit_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    position INTEGER NOT NULL CHECK (position > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'WAITING'
        CHECK (status IN ('WAITING','IN_PROGRESS','COMPLETED','SKIPPED')),
    doctor_notes TEXT,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    skipped_at TIMESTAMPTZ,
    skipped_by BIGINT,
    skip_reason VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (visit_id, doctor_id),
    UNIQUE (visit_id, position),
    FOREIGN KEY (hospital_id, visit_id) REFERENCES visits(hospital_id, id) ON DELETE CASCADE,
    FOREIGN KEY (hospital_id, doctor_id) REFERENCES users(hospital_id, id),
    FOREIGN KEY (hospital_id, skipped_by) REFERENCES users(hospital_id, id)
);

CREATE INDEX idx_visit_doctors_queue ON visit_doctors(hospital_id, doctor_id, status, visit_id);

CREATE TABLE visit_charges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
    visit_id BIGINT NOT NULL,
    billing_item_id BIGINT,
    description VARCHAR(180) NOT NULL,
    amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    source VARCHAR(20) NOT NULL CHECK (source IN ('DOCTOR','RECEPTION')),
    added_by BIGINT NOT NULL,
    doctor_id BIGINT,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    is_voided BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (hospital_id, visit_id) REFERENCES visits(hospital_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (hospital_id, billing_item_id) REFERENCES billing_items(hospital_id, id),
    FOREIGN KEY (hospital_id, added_by) REFERENCES users(hospital_id, id),
    FOREIGN KEY (hospital_id, doctor_id) REFERENCES users(hospital_id, id)
);

CREATE INDEX idx_visit_charges_visit ON visit_charges(hospital_id, visit_id);

CREATE TABLE visit_charge_corrections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
    visit_id BIGINT NOT NULL,
    visit_charge_id BIGINT NOT NULL REFERENCES visit_charges(id),
    action VARCHAR(20) NOT NULL CHECK (action IN ('REDUCE', 'REMOVE')),
    description VARCHAR(180) NOT NULL,
    old_amount NUMERIC(12,2) NOT NULL CHECK (old_amount >= 0),
    new_amount NUMERIC(12,2) NOT NULL CHECK (new_amount >= 0),
    old_total NUMERIC(12,2) NOT NULL CHECK (old_total >= 0),
    new_total NUMERIC(12,2) NOT NULL CHECK (new_total >= 0),
    recorded_payment_amount NUMERIC(12,2) CHECK (recorded_payment_amount IS NULL OR recorded_payment_amount >= 0),
    reason TEXT NOT NULL CHECK (char_length(trim(reason)) >= 5),
    corrected_by BIGINT NOT NULL,
    corrected_by_role VARCHAR(20) NOT NULL CHECK (corrected_by_role IN ('ADMIN', 'DOCTOR', 'RECEPTIONIST')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (hospital_id, visit_id) REFERENCES visits(hospital_id, id),
    FOREIGN KEY (hospital_id, corrected_by) REFERENCES users(hospital_id, id)
);

CREATE INDEX idx_visit_charge_corrections_visit ON visit_charge_corrections(hospital_id, visit_id, created_at DESC);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
    visit_id BIGINT NOT NULL,
    amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    payment_mode VARCHAR(20) NOT NULL CHECK (payment_mode IN ('CASH','UPI','CARD','OTHER')),
    reference_no VARCHAR(120),
    accepted_by BIGINT NOT NULL,
    paid_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (hospital_id, visit_id),
    UNIQUE (hospital_id, id),
    FOREIGN KEY (hospital_id, visit_id) REFERENCES visits(hospital_id, id),
    FOREIGN KEY (hospital_id, accepted_by) REFERENCES users(hospital_id, id)
);

CREATE INDEX idx_payments_hospital_paid ON payments(hospital_id, paid_at DESC);

CREATE TABLE payment_doctor_settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
    payment_id BIGINT NOT NULL,
    visit_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    settled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (hospital_id,payment_id,doctor_id),
    FOREIGN KEY (hospital_id,payment_id) REFERENCES payments(hospital_id,id) ON DELETE CASCADE,
    FOREIGN KEY (hospital_id,visit_id) REFERENCES visits(hospital_id,id),
    FOREIGN KEY (hospital_id,doctor_id) REFERENCES users(hospital_id,id)
);

CREATE INDEX idx_payment_doctor_settlements_doctor ON payment_doctor_settlements(hospital_id,doctor_id,settled_at DESC);

COMMIT;
