BEGIN;

ALTER TABLE visit_charges
  ADD COLUMN IF NOT EXISTS is_voided BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS visit_charge_corrections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
    visit_id BIGINT NOT NULL,
    visit_charge_id BIGINT NOT NULL REFERENCES visit_charges(id),
    action VARCHAR(20) NOT NULL CHECK (action IN ('REDUCE', 'REMOVE')),
    description VARCHAR(180) NOT NULL,
    old_amount NUMERIC(12,2) NOT NULL CHECK (old_amount >= 0),
    new_amount NUMERIC(12,2) NOT NULL CHECK (new_amount >= 0),
    old_total NUMERIC(12,2) NOT NULL CHECK (old_total >= 0),
    new_total NUMERIC(12,2) NOT NULL CHECK (new_total >= 0),
    recorded_payment_amount NUMERIC(12,2) CHECK (recorded_payment_amount IS NULL OR recorded_payment_amount >= 0),
    reason TEXT NOT NULL CHECK (char_length(trim(reason)) >= 5),
    corrected_by BIGINT NOT NULL,
    corrected_by_role VARCHAR(20) NOT NULL CHECK (corrected_by_role IN ('ADMIN', 'DOCTOR', 'RECEPTIONIST')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (hospital_id, visit_id) REFERENCES visits(hospital_id, id),
    FOREIGN KEY (hospital_id, corrected_by) REFERENCES users(hospital_id, id)
);

CREATE INDEX IF NOT EXISTS idx_visit_charge_corrections_visit
  ON visit_charge_corrections(hospital_id, visit_id, created_at DESC);

COMMIT;
