BEGIN;

CREATE TABLE IF NOT EXISTS visit_doctors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
  visit_id BIGINT NOT NULL,
  doctor_id BIGINT NOT NULL,
  position INTEGER NOT NULL CHECK (position > 0),
  status VARCHAR(20) NOT NULL DEFAULT 'WAITING'
    CHECK (status IN ('WAITING','IN_PROGRESS','COMPLETED')),
  doctor_notes TEXT,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (visit_id, doctor_id),
  UNIQUE (visit_id, position),
  FOREIGN KEY (hospital_id, visit_id) REFERENCES visits(hospital_id, id) ON DELETE CASCADE,
  FOREIGN KEY (hospital_id, doctor_id) REFERENCES users(hospital_id, id)
);

CREATE INDEX IF NOT EXISTS idx_visit_doctors_queue
  ON visit_doctors(hospital_id, doctor_id, status, visit_id);

INSERT INTO visit_doctors(hospital_id,visit_id,doctor_id,position,status,doctor_notes,started_at,completed_at)
SELECT v.hospital_id,v.id,v.doctor_id,1,
       CASE
         WHEN v.status='WITH_DOCTOR' THEN 'IN_PROGRESS'
         WHEN v.status IN ('PAYMENT_PENDING','LEFT_WITHOUT_PAYMENT','COMPLETED') THEN 'COMPLETED'
         ELSE 'WAITING'
       END,
       v.doctor_notes,
       CASE WHEN v.status IN ('WITH_DOCTOR','PAYMENT_PENDING','LEFT_WITHOUT_PAYMENT','COMPLETED') THEN v.updated_at END,
       CASE WHEN v.status IN ('PAYMENT_PENDING','LEFT_WITHOUT_PAYMENT','COMPLETED') THEN COALESCE(v.completed_at,v.updated_at) END
FROM visits v
WHERE NOT EXISTS (SELECT 1 FROM visit_doctors vd WHERE vd.visit_id=v.id);

COMMIT;
