BEGIN;

ALTER TABLE visit_charges
  ADD COLUMN IF NOT EXISTS doctor_id BIGINT;

UPDATE visit_charges vc
SET doctor_id=COALESCE(
  (SELECT vd.doctor_id
   FROM visit_doctors vd
   WHERE vd.hospital_id=vc.hospital_id AND vd.visit_id=vc.visit_id AND vd.doctor_id=vc.added_by
   LIMIT 1),
  v.doctor_id
)
FROM visits v
WHERE vc.visit_id=v.id AND vc.hospital_id=v.hospital_id
  AND vc.source='DOCTOR' AND vc.doctor_id IS NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname='visit_charges_doctor_id_fkey' AND conrelid='visit_charges'::regclass
  ) THEN
    ALTER TABLE visit_charges
      ADD CONSTRAINT visit_charges_doctor_id_fkey
      FOREIGN KEY (hospital_id,doctor_id) REFERENCES users(hospital_id,id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_visit_charges_doctor
  ON visit_charges(hospital_id,visit_id,doctor_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname='payments_hospital_id_id_key' AND conrelid='payments'::regclass
  ) THEN
    ALTER TABLE payments ADD CONSTRAINT payments_hospital_id_id_key UNIQUE (hospital_id,id);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS payment_doctor_settlements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
  payment_id BIGINT NOT NULL,
  visit_id BIGINT NOT NULL,
  doctor_id BIGINT NOT NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
  settled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (hospital_id,payment_id,doctor_id),
  FOREIGN KEY (hospital_id,payment_id) REFERENCES payments(hospital_id,id) ON DELETE CASCADE,
  FOREIGN KEY (hospital_id,visit_id) REFERENCES visits(hospital_id,id),
  FOREIGN KEY (hospital_id,doctor_id) REFERENCES users(hospital_id,id)
);

CREATE INDEX IF NOT EXISTS idx_payment_doctor_settlements_doctor
  ON payment_doctor_settlements(hospital_id,doctor_id,settled_at DESC);

INSERT INTO payment_doctor_settlements(hospital_id,payment_id,visit_id,doctor_id,amount,settled_at)
SELECT p.hospital_id,p.id,p.visit_id,vd.doctor_id,
       COALESCE(SUM(vc.amount) FILTER (WHERE vc.doctor_id=vd.doctor_id),0)::numeric(12,2),p.paid_at
FROM payments p
JOIN visit_doctors vd ON vd.hospital_id=p.hospital_id AND vd.visit_id=p.visit_id
LEFT JOIN visit_charges vc ON vc.hospital_id=p.hospital_id AND vc.visit_id=p.visit_id AND vc.source='DOCTOR'
WHERE NOT EXISTS (
  SELECT 1 FROM payment_doctor_settlements pds
  WHERE pds.hospital_id=p.hospital_id AND pds.payment_id=p.id AND pds.doctor_id=vd.doctor_id
)
GROUP BY p.hospital_id,p.id,p.visit_id,vd.doctor_id,p.paid_at;

COMMIT;
