BEGIN;

CREATE TABLE IF NOT EXISTS platform_superusers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE hospitals
  ADD COLUMN IF NOT EXISTS deactivated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS deactivated_by_superuser BIGINT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname='hospitals_deactivated_by_superuser_fkey' AND conrelid='hospitals'::regclass
  ) THEN
    ALTER TABLE hospitals
      ADD CONSTRAINT hospitals_deactivated_by_superuser_fkey
      FOREIGN KEY (deactivated_by_superuser) REFERENCES platform_superusers(id);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS super_admin_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  superuser_id BIGINT NOT NULL REFERENCES platform_superusers(id),
  action VARCHAR(50) NOT NULL CHECK (action IN ('LOGIN','IMPERSONATE_ADMIN','IMPERSONATE_USER','DEACTIVATE_HOSPITAL','ACTIVATE_HOSPITAL')),
  hospital_id BIGINT REFERENCES hospitals(id),
  target_user_id BIGINT REFERENCES users(id),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_super_admin_audit_created ON super_admin_audit_logs(superuser_id,created_at DESC);

COMMIT;
