-- Platform billing: per-doctor subscription invoices raised by the Super Admin to each hospital.
BEGIN;

-- Per-hospital billing settings (GST is optional, decided per hospital, and always added on top).
ALTER TABLE hospitals
  ADD COLUMN IF NOT EXISTS billing_start_date DATE,
  ADD COLUMN IF NOT EXISTS billing_cycle VARCHAR(10) NOT NULL DEFAULT 'ANNUAL',
  ADD COLUMN IF NOT EXISTS gst_applicable BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS gst_rate NUMERIC(5,2) NOT NULL DEFAULT 18,
  ADD COLUMN IF NOT EXISTS gstin VARCHAR(15);

UPDATE hospitals SET billing_start_date = created_at::date WHERE billing_start_date IS NULL;
ALTER TABLE hospitals ALTER COLUMN billing_start_date SET DEFAULT CURRENT_DATE;
ALTER TABLE hospitals ALTER COLUMN billing_start_date SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='hospitals_billing_cycle_check' AND conrelid='hospitals'::regclass) THEN
    ALTER TABLE hospitals ADD CONSTRAINT hospitals_billing_cycle_check CHECK (billing_cycle IN ('MONTHLY','ANNUAL'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='hospitals_gst_rate_check' AND conrelid='hospitals'::regclass) THEN
    ALTER TABLE hospitals ADD CONSTRAINT hospitals_gst_rate_check CHECK (gst_rate >= 0 AND gst_rate <= 40);
  END IF;
END $$;

-- Single-doctor base rates, effective-dated. The row in force on a date decides the rate;
-- an upcoming row (effective_from in the future) is a scheduled rate change.
CREATE TABLE IF NOT EXISTS platform_rate_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year1_base NUMERIC(10,2) NOT NULL CHECK (year1_base > 0),
  year2_base NUMERIC(10,2) NOT NULL CHECK (year2_base > 0),
  effective_from DATE NOT NULL,
  apply_to_existing BOOLEAN NOT NULL DEFAULT TRUE,
  reason VARCHAR(500),
  created_by BIGINT REFERENCES platform_superusers(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  cancelled_at TIMESTAMPTZ,
  cancelled_by BIGINT REFERENCES platform_superusers(id)
);
CREATE INDEX IF NOT EXISTS idx_platform_rate_plans_effective ON platform_rate_plans(effective_from DESC) WHERE cancelled_at IS NULL;

INSERT INTO platform_rate_plans(year1_base,year2_base,effective_from,apply_to_existing,reason)
SELECT 799,899,DATE '2000-01-01',TRUE,'Initial rates'
WHERE NOT EXISTS (SELECT 1 FROM platform_rate_plans);

CREATE SEQUENCE IF NOT EXISTS platform_invoice_no_seq START 1;

CREATE TABLE IF NOT EXISTS platform_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no VARCHAR(30) NOT NULL UNIQUE,
  hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
  cycle VARCHAR(10) NOT NULL CHECK (cycle IN ('MONTHLY','ANNUAL')),
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  doctors INTEGER NOT NULL CHECK (doctors > 0),
  rate_year SMALLINT NOT NULL CHECK (rate_year IN (1,2)),
  base_rate NUMERIC(10,2) NOT NULL,
  tier_label VARCHAR(10) NOT NULL,
  discount_pct NUMERIC(5,2) NOT NULL,
  rate NUMERIC(10,2) NOT NULL,
  months INTEGER NOT NULL CHECK (months > 0),
  subtotal NUMERIC(12,2) NOT NULL,
  adjustment NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (adjustment >= 0),
  adjustment_reason VARCHAR(300),
  gst_applicable BOOLEAN NOT NULL DEFAULT FALSE,
  gst_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
  gst_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  gstin VARCHAR(15),
  total NUMERIC(12,2) NOT NULL,
  status VARCHAR(12) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','ISSUED','PAID','CANCELLED')),
  issue_date DATE,
  due_date DATE,
  paid_on DATE,
  paid_amount NUMERIC(12,2),
  payment_mode VARCHAR(20),
  payment_reference VARCHAR(80),
  payment_note VARCHAR(300),
  notes VARCHAR(500),
  cancel_reason VARCHAR(300),
  created_by BIGINT REFERENCES platform_superusers(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_platform_invoices_hospital ON platform_invoices(hospital_id, period_start DESC);
CREATE INDEX IF NOT EXISTS idx_platform_invoices_status ON platform_invoices(status, due_date);
CREATE UNIQUE INDEX IF NOT EXISTS uq_platform_invoices_period ON platform_invoices(hospital_id, period_start) WHERE status <> 'CANCELLED';

-- Company details printed on every invoice (edited from the Pricing tab).
CREATE TABLE IF NOT EXISTS platform_billing_company (
  id SMALLINT PRIMARY KEY CHECK (id = 1),
  name VARCHAR(160) NOT NULL DEFAULT 'CareBill Platform',
  address TEXT,
  gstin VARCHAR(15),
  payment_details TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by BIGINT REFERENCES platform_superusers(id)
);
INSERT INTO platform_billing_company(id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- Audit trail: allow the new billing actions.
DO $$
DECLARE c TEXT;
BEGIN
  FOR c IN SELECT conname FROM pg_constraint WHERE conrelid='super_admin_audit_logs'::regclass AND contype='c' AND pg_get_constraintdef(oid) LIKE '%IMPERSONATE_ADMIN%'
  LOOP
    EXECUTE format('ALTER TABLE super_admin_audit_logs DROP CONSTRAINT %I', c);
  END LOOP;
  ALTER TABLE super_admin_audit_logs ADD CONSTRAINT super_admin_audit_logs_action_check CHECK (action IN (
    'LOGIN','IMPERSONATE_ADMIN','IMPERSONATE_USER','DEACTIVATE_HOSPITAL','ACTIVATE_HOSPITAL',
    'RATE_SCHEDULED','RATE_UPDATED','RATE_CANCELLED','HOSPITAL_BILLING_UPDATED',
    'INVOICE_CREATED','INVOICE_ISSUED','INVOICE_PAID','INVOICE_CANCELLED','COMPANY_DETAILS_UPDATED'));
END $$;

COMMIT;
