-- Doctor-based billing: a history of when doctors were active, and top-up invoices for annual clinics.
BEGIN;

-- 1. When a doctor became (in)active. Written by a trigger so every code path is covered.
CREATE TABLE IF NOT EXISTS doctor_status_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id BIGINT NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL,
  active BOOLEAN NOT NULL,
  at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_doctor_status_events_user ON doctor_status_events(user_id, at);
CREATE INDEX IF NOT EXISTS idx_doctor_status_events_hospital ON doctor_status_events(hospital_id, at);

CREATE OR REPLACE FUNCTION log_doctor_status() RETURNS trigger AS $$
DECLARE
  was BOOLEAN := FALSE;
  now_active BOOLEAN;
BEGIN
  IF TG_OP = 'UPDATE' THEN was := (OLD.role = 'DOCTOR' AND OLD.is_active AND OLD.deleted_at IS NULL); END IF;
  now_active := (NEW.role = 'DOCTOR' AND NEW.is_active AND NEW.deleted_at IS NULL);
  IF now_active <> was THEN
    INSERT INTO doctor_status_events(hospital_id, user_id, active) VALUES (NEW.hospital_id, NEW.id, now_active);
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_log_doctor_status ON users;
CREATE TRIGGER trg_log_doctor_status AFTER INSERT OR UPDATE OF is_active, role, deleted_at ON users
  FOR EACH ROW EXECUTE FUNCTION log_doctor_status();

-- Backfill: every existing doctor was active from creation; inactive/deleted ones stopped at their last change.
INSERT INTO doctor_status_events(hospital_id, user_id, active, at)
SELECT u.hospital_id, u.id, TRUE, u.created_at FROM users u
WHERE u.role = 'DOCTOR' AND NOT EXISTS (SELECT 1 FROM doctor_status_events e WHERE e.user_id = u.id);
INSERT INTO doctor_status_events(hospital_id, user_id, active, at)
SELECT u.hospital_id, u.id, FALSE, COALESCE(u.deleted_at, u.updated_at) FROM users u
WHERE u.role = 'DOCTOR' AND (NOT u.is_active OR u.deleted_at IS NOT NULL)
  AND NOT EXISTS (SELECT 1 FROM doctor_status_events e WHERE e.user_id = u.id AND e.active = FALSE);

-- 2. Top-up invoices (annual clinics that add doctors beyond what the year was billed for).
ALTER TABLE platform_invoices
  ADD COLUMN IF NOT EXISTS kind VARCHAR(10) NOT NULL DEFAULT 'PERIOD',
  ADD COLUMN IF NOT EXISTS parent_id BIGINT REFERENCES platform_invoices(id),
  ADD COLUMN IF NOT EXISTS prev_doctors INTEGER,
  ADD COLUMN IF NOT EXISTS prev_rate NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS prorate_days INTEGER,
  ADD COLUMN IF NOT EXISTS period_days INTEGER;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='platform_invoices_kind_check' AND conrelid='platform_invoices'::regclass) THEN
    ALTER TABLE platform_invoices ADD CONSTRAINT platform_invoices_kind_check CHECK (kind IN ('PERIOD','TOPUP'));
  END IF;
END $$;
DROP INDEX IF EXISTS uq_platform_invoices_period;
CREATE UNIQUE INDEX IF NOT EXISTS uq_platform_invoices_period ON platform_invoices(hospital_id, period_start) WHERE status <> 'CANCELLED' AND kind = 'PERIOD';

COMMIT;
