-- Prescriptions: the medicines a doctor prescribes during a visit (one list per doctor per visit).
-- Each line copies the medicine's name/composition/pack, so an old prescription still prints the same
-- even if the global `medicines` catalogue is re-imported later. medicine_id is NULL for a custom medicine.
BEGIN;

CREATE TABLE IF NOT EXISTS visit_prescription_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id BIGINT NOT NULL REFERENCES hospitals(id),
  visit_id BIGINT NOT NULL,
  doctor_id BIGINT NOT NULL,
  position INTEGER NOT NULL CHECK (position > 0),
  medicine_id BIGINT,
  name VARCHAR(200) NOT NULL,
  composition VARCHAR(300) NOT NULL DEFAULT '',
  manufacturer VARCHAR(200) NOT NULL DEFAULT '',
  pack_size VARCHAR(120) NOT NULL DEFAULT '',
  dose VARCHAR(40) NOT NULL DEFAULT '',
  timing VARCHAR(12) NOT NULL DEFAULT 'ANY' CHECK (timing IN ('BEFORE_FOOD','AFTER_FOOD','ANY')),
  duration_days INTEGER CHECK (duration_days IS NULL OR duration_days BETWEEN 1 AND 365),
  note VARCHAR(200) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (visit_id, doctor_id, position),
  FOREIGN KEY (hospital_id, visit_id) REFERENCES visits(hospital_id, id) ON DELETE CASCADE,
  FOREIGN KEY (hospital_id, doctor_id) REFERENCES users(hospital_id, id)
);
CREATE INDEX IF NOT EXISTS idx_visit_prescription_items_visit ON visit_prescription_items(hospital_id, visit_id);
CREATE INDEX IF NOT EXISTS idx_visit_prescription_items_doctor ON visit_prescription_items(hospital_id, doctor_id, medicine_id);

-- Typing-as-you-search over the catalogue: "contains" matches on the name or either ingredient.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
DO $$
BEGIN
  IF to_regclass('public.medicines') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS medicines_name_trgm_idx ON medicines USING gin (lower(name) gin_trgm_ops);
    CREATE INDEX IF NOT EXISTS medicines_composition_trgm_idx ON medicines USING gin (lower(short_composition1 || ' ' || short_composition2) gin_trgm_ops);
  END IF;
END $$;

COMMIT;
