-- Hospital expenses: money the hospital spends (rent, salaries, supplies...).
-- Categories belong to each hospital (admins can add their own); the CareBill subscription is not stored here:
-- once an invoice is paid it is listed automatically as an expense, read straight from platform_invoices.
BEGIN;

CREATE TABLE IF NOT EXISTS expense_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id BIGINT NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
  name VARCHAR(40) NOT NULL,
  color VARCHAR(7) NOT NULL DEFAULT '#667085',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (hospital_id, id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_expense_categories_name ON expense_categories(hospital_id, lower(name));

CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id BIGINT NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
  expense_date DATE NOT NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  category_id BIGINT NOT NULL,
  paid_to VARCHAR(160) NOT NULL DEFAULT '',
  payment_mode VARCHAR(10) NOT NULL DEFAULT 'CASH' CHECK (payment_mode IN ('CASH','UPI','CARD','BANK')),
  note VARCHAR(500) NOT NULL DEFAULT '',
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (hospital_id, category_id) REFERENCES expense_categories(hospital_id, id),
  FOREIGN KEY (hospital_id, created_by) REFERENCES users(hospital_id, id)
);
CREATE INDEX IF NOT EXISTS idx_expenses_hospital_date ON expenses(hospital_id, expense_date DESC) WHERE deleted_at IS NULL;

COMMIT;
